/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.connection.Conexao;
import br.com.dao.MarcaDao;
import br.com.dao.MarcaDaoImpl;
import br.com.dao.NotebookDao;
import br.com.dao.NotebookDaoImpl;
import br.com.model.Marca;
import br.com.model.Notebook;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class FrmCadNotebook extends javax.swing.JInternalFrame {

    int indice = 0;
    int idincrement = 0;
    List<Notebook> lista = new ArrayList<Notebook>();
    List<Marca> marcas = new ArrayList<Marca>();
    NotebookDao notebookDao = new NotebookDaoImpl();
    MarcaDao marcaDao = new MarcaDaoImpl();

    /**
     * Creates new form FrmCadNotebook
     */
    public FrmCadNotebook() {
        initComponents();
        Connection conexao = new Conexao().getConnection();
        
        txtId.setEnabled(false);
        lista = notebookDao.getNotebooks();
        marcas = marcaDao.getMarcas();
        preencheMarcas();
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ainda não foram cadastrados Notebooks");
        } else {
            mostrarDados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        rbConvencional = new javax.swing.JRadioButton();
        rbGamer = new javax.swing.JRadioButton();
        lblTipoNotebook = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        cbxMarca = new javax.swing.JComboBox<>();
        txtSerie = new javax.swing.JFormattedTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblIconeNotebook = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNotebooks = new javax.swing.JTable();
        lblIconeLista = new javax.swing.JLabel();
        lblTituloLista = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setForeground(new java.awt.Color(204, 204, 255));
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Notebooks");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastro de Notebooks");

        lblId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblId.setText("Id:");

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModelo.setText("Modelo:");

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMarca.setText("Marca:");

        lblSerie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSerie.setText("Série:");

        rbConvencional.setBackground(new java.awt.Color(204, 204, 255));
        grupoTipo.add(rbConvencional);
        rbConvencional.setText("Convencional");

        rbGamer.setBackground(new java.awt.Color(204, 204, 255));
        grupoTipo.add(rbGamer);
        rbGamer.setText("Gamer");

        lblTipoNotebook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipoNotebook.setText("Tipo de Notebook:");

        try {
            txtSerie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/img_adicionar_black.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/img_salvar_black.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/img_editar_black.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/img_excluir_black.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblIconeNotebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/notebook-icon.png"))); // NOI18N

        tbNotebooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Marca", "Série", "Tipo"
            }
        ));
        tbNotebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNotebooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNotebooks);

        lblIconeLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/notebook-list.png"))); // NOI18N

        lblTituloLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloLista.setText("Lista de Notebooks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblIconeNotebook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblModelo)
                            .addComponent(lblId)
                            .addComponent(lblMarca)
                            .addComponent(lblSerie)
                            .addComponent(lblTipoNotebook)
                            .addComponent(txtModelo)
                            .addComponent(txtId)
                            .addComponent(txtSerie)
                            .addComponent(cbxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNovo)
                                    .addComponent(btnPrimeiro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnProximo)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnUltimo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnExcluir))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbConvencional)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAnterior)
                                    .addComponent(rbGamer))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIconeLista)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloLista)
                        .addGap(144, 144, 144))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblTituloLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconeNotebook)
                    .addComponent(lblIconeLista))
                .addGap(20, 20, 20)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblTipoNotebook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbConvencional)
                            .addComponent(rbGamer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrimeiro)
                            .addComponent(btnAnterior)
                            .addComponent(btnProximo)
                            .addComponent(btnUltimo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnSalvar)
                            .addComponent(btnEditar)
                            .addComponent(btnExcluir)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        indice = 0;
        mostrarDados();
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indice--;
        if (indice < 0) {
            indice++;
            JOptionPane.showMessageDialog(this, "Você já está no primeiro registro");
        }
        mostrarDados();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        indice++;
        if (indice > lista.size() - 1) {
            indice--;
            JOptionPane.showMessageDialog(this, "Você já está no último registro");
        } else {
            mostrarDados();
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        indice = lista.size()-1;
        mostrarDados();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        idincrement++;
        txtId.setText(""+idincrement);
        txtModelo.setText("");
        cbxMarca.setSelectedItem("--Selecionar--");
        txtSerie.setText("");
        grupoTipo.clearSelection();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int MarcaId = marcaDao.buscarId(cbxMarca.getSelectedItem().toString());
        
        Notebook notebook = new Notebook();
        notebook.setId(Integer.parseInt(txtId.getText()));
        notebook.setModelo(txtModelo.getText());
        notebook.setMarca(MarcaId);
        notebook.setSerie(txtSerie.getText());
        if (rbConvencional.isSelected()) {
            notebook.setTipo(rbConvencional.getText());
        }
        if (rbGamer.isSelected()) {
            notebook.setTipo(rbGamer.getText());
        }
        
        notebookDao.salvarNotebook(notebook);
        lista.clear();
        lista = notebookDao.getNotebooks();
        indice = lista.size() - 1;
        mostrarDados();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int MarcaId = marcaDao.buscarId(cbxMarca.getSelectedItem().toString());
        
        Notebook notebook = new Notebook();
        notebook.setId(Integer.parseInt(txtId.getText()));
        notebook.setModelo(txtModelo.getText());
        notebook.setMarca(MarcaId);
        notebook.setSerie(txtSerie.getText());
        if (rbConvencional.isSelected()) {
            notebook.setTipo(rbConvencional.getText());
        }
        if (rbGamer.isSelected()) {
            notebook.setTipo(rbGamer.getText());
        }
        
        notebookDao.alterarNotebook(notebook);
        lista.clear();
        lista = notebookDao.getNotebooks();
        indice = lista.size() - 1;
        mostrarDados();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = (Integer.parseInt(txtId.getText()));
                
        notebookDao.excluirNotebook(id);
        lista.clear();
        lista = notebookDao.getNotebooks();
        indice = lista.size() - 1;
        mostrarDados();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tbNotebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNotebooksMouseClicked
        int indiceDaTabela = tbNotebooks.getSelectedRow();
        txtId.setText("" + tbNotebooks.getValueAt(indiceDaTabela, 0));
        txtModelo.setText(tbNotebooks.getValueAt(indiceDaTabela, 1).toString());
        cbxMarca.setSelectedItem(tbNotebooks.getValueAt(indiceDaTabela, 2).toString());
        txtSerie.setText(tbNotebooks.getValueAt(indiceDaTabela, 3).toString());
        if (lista.get(indiceDaTabela).getTipo().equals("Convencional")) {
            rbConvencional.setText(tbNotebooks.getValueAt(indiceDaTabela, 4).toString());
        }
        if (lista.get(indiceDaTabela).getTipo().equals("Gamer")) {
            rbGamer.setText(tbNotebooks.getValueAt(indiceDaTabela, 4).toString());
        }
    }//GEN-LAST:event_tbNotebooksMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIconeLista;
    private javax.swing.JLabel lblIconeNotebook;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTipoNotebook;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloLista;
    private javax.swing.JRadioButton rbConvencional;
    private javax.swing.JRadioButton rbGamer;
    private javax.swing.JTable tbNotebooks;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    public void mostrarDados() {
        txtId.setText("" + lista.get(indice).getId());
        txtModelo.setText(lista.get(indice).getModelo());
        cbxMarca.setSelectedItem(buscarDescricaoMarca(lista.get(indice).getMarca()));
        txtSerie.setText(lista.get(indice).getSerie());
        if (lista.get(indice).getTipo().equals("Convencional")) {
            rbConvencional.setSelected(true);
        }
        if (lista.get(indice).getTipo().equals("Gamer")) {
            rbGamer.setSelected(true);
        }
        preencheTabela();
    }
    
    public void preencheTabela() {
        tbNotebooks.getColumnModel().getColumn(0).setPreferredWidth(20);
        
        DefaultTableModel modelo = (DefaultTableModel)tbNotebooks.getModel();
        
        modelo.setNumRows(0);
        for(int i=0; i < lista.size(); i++) {
            modelo.addRow(new Object[]{lista.get(i).getId(), lista.get(i).getModelo(), lista.get(i).getMarca(), lista.get(i).getSerie(), lista.get(i).getTipo()});
        }
    }
    
    public void preencheMarcas() {
        cbxMarca.addItem("--Selecione--");
        for (int i = 0; i < marcas.size(); i++) {
            cbxMarca.addItem(marcas.get(i).getDescricao());
        }
    }
    
    public String buscarDescricaoMarca(int id) {
        String marca = null;
        for (int i = 0; i < marcas.size(); i++) {
            if (marcas.get(i).getId() == id) {
                marca = marcas.get(i).getDescricao();
            }
        }
        return marca;
    }
}
